services:

  app:
    container_name: node-mysql
    build: .
    ports:
      - "8200:3000"
    links:
      - mysql
    depends_on:
      - mysql
    restart: unless-stopped
    command: npm start

  mysql:
    container_name: mysql
    image: mysql:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: node_crud
    expose:
      - 3306
    restart: unless-stopped
    
