services:

  app:
    container_name: eventos
    build: .
    ports:
      - "8200:3000"
    links:
      - mysql
    depends_on:
      - mysql
    restart: unless-stopped
    command: npm start

  mysql:
    container_name: eventos_db
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: node_crud
    volumes:
      - ./db:/var/lib/mysql
    expose:
      - 3306
    restart: unless-stopped
    
